"""Tests for docx_generator.

Asserts the structural contract that NotebookLM (and our pipeline) depends on:
each utterance is one paragraph with a bold timestamp, a speaker line carrying
the role tag, and the utterance text. Also asserts the page header has the
title left and "Meeting created at: …" right, mirroring Fireflies' template.
"""
import os

import pytest
from docx import Document
from docx.oxml.ns import qn

import docx_generator
from fireflies import Sentence, Transcript


def _make_transcript(**overrides):
    base = dict(
        id="cb4abf7f-aaaa-bbbb-cccc-dddddddddddd",
        title="Meeting with Klara (David Abadin)",
        date=1745272200000,  # ms; gives a deterministic date string
        duration=5340,
        participants=["Elman Amador Medina", "Klara Klarowicz", "David Abadin"],
        sentences=[
            Sentence(0, "Elman Amador Medina", "Hey, David. How are you?", 2.0, 3.0),
            Sentence(1, "David Abadin", "I'm good. How are you?", 3.0, 5.0),
            Sentence(2, "David Abadin", "Long story short.", 5340.0, 5360.0),
        ],
        summary_overview="",
        summary_action_items=[],
        summary_keywords=[],
    )
    base.update(overrides)
    return Transcript(**base)


@pytest.fixture
def role_map():
    return {
        "Elman Amador Medina": "internal",
        "Klara Klarowicz": "internal",
        "David Abadin": "external",
    }


def test_generate_writes_docx_to_output_dir(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    assert os.path.exists(path)
    assert path.endswith(".docx")
    assert "meeting-with-klara-david-abadin" in os.path.basename(path)


def test_each_sentence_becomes_one_paragraph(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    # 3 utterance paragraphs + 1 footer ("Generated by broccoli-ai") = 4
    assert len(doc.paragraphs) == 4
    assert doc.paragraphs[-1].text == "Generated by broccoli-ai"


def test_utterance_paragraph_has_bold_timestamp_then_speaker_then_text(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    p = doc.paragraphs[0]
    # 3 runs separated by <w:br/>
    assert len(p.runs) == 3
    ts, speaker, text = p.runs
    assert ts.bold is True
    assert ts.text.strip() == "00:02"
    assert speaker.text.strip() == "Elman Amador Medina [BROCCOLI TEAM]"
    assert text.text.strip() == "Hey, David. How are you?"


def test_external_speaker_gets_interviewee_tag(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    # Second utterance is David Abadin (external)
    speaker_run = doc.paragraphs[1].runs[1]
    assert speaker_run.text.strip() == "David Abadin [INTERVIEWEE]"


def test_long_meeting_uses_hms_timestamp(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    # Third utterance starts at 5340s = 1:29:00
    ts_run = doc.paragraphs[2].runs[0]
    assert ts_run.text.strip() == "01:29:00"


def test_unknown_speaker_falls_back_to_interviewee(tmp_path):
    t = _make_transcript(sentences=[Sentence(0, "Stranger", "Hello", 1.0, 2.0)])
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map={})
    doc = Document(path)
    speaker_run = doc.paragraphs[0].runs[1]
    assert speaker_run.text.strip() == "Stranger [INTERVIEWEE]"


def test_header_has_title_left_and_creation_date_right(tmp_path, role_map):
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    header = doc.sections[0].header
    # Header should contain a 2-col table with the title in the first cell and
    # "Meeting created at: …" in the second cell.
    tables = header.tables
    assert len(tables) == 1
    cells = tables[0].rows[0].cells
    assert len(cells) == 2
    assert cells[0].paragraphs[0].text == "Meeting with Klara (David Abadin)"
    assert cells[1].paragraphs[0].text.startswith("Meeting created at: ")


def test_header_table_borders_are_invisible(tmp_path, role_map):
    """Mirrors Fireflies' borderless 2-col header — no visual divider."""
    t = _make_transcript()
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    table = doc.sections[0].header.tables[0]
    borders = table._tbl.tblPr.find(qn("w:tblBorders"))
    assert borders is not None
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        elem = borders.find(qn(f"w:{edge}"))
        assert elem is not None
        assert elem.get(qn("w:val")) == "nil"


def test_empty_transcript_does_not_raise(tmp_path, role_map):
    t = _make_transcript(sentences=[])
    path = docx_generator.generate_transcript_docx(t, str(tmp_path), role_map=role_map)
    doc = Document(path)
    # Single placeholder paragraph + footer
    assert any("(No transcript available)" in p.text for p in doc.paragraphs)
