#!/usr/bin/env python3
"""
HTTP proxy: wraps `claude -p` as an Anthropic Messages API endpoint.

LiteLLM (and BAML, and anything else that speaks Anthropic API) can POST
to this and get a response generated by Claude Code CLI, which uses your
Max subscription — zero per-token cost.

Endpoint: POST /v1/messages   (matches api.anthropic.com path)
Request body: standard Anthropic Messages API shape
  { "model": "claude-haiku-4-5", "system": "...", "messages": [...] }
Model selection: passed through to `claude --model <name>` when present.

Usage:
    python3 claude-proxy.py              # listens on 0.0.0.0:8199
    python3 claude-proxy.py --port 8200  # custom port

Bind address: 0.0.0.0 so the litellm container can reach us via the
docker bridge gateway. The VM's GCP firewall does NOT expose 8199
externally, so this stays VM-internal.
"""

import argparse
import json
import subprocess
import sys
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


# Map common short model names to the flag value `claude` CLI accepts.
# Anything not in this map is passed through verbatim.
MODEL_ALIASES = {
    "claude-sonnet-4-6": "sonnet",
    "claude-sonnet-4-5": "sonnet",
    "claude-sonnet": "sonnet",
    "claude-haiku-4-5": "haiku",
    "claude-haiku": "haiku",
    "claude-opus-4-7": "opus",
    "claude-opus": "opus",
}


class ClaudeProxyHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        # Tiny health check so deploy.yml can curl us and fail loudly.
        if self.path == "/health":
            self._send_json(200, {"status": "ok"})
            return
        self._send_json(404, {"error": "not_found", "path": self.path})

    def do_POST(self):
        if self.path not in ("/v1/messages", "/"):
            self._send_json(404, {"error": "not_found", "path": self.path})
            return

        content_length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(content_length))
        except json.JSONDecodeError as exc:
            self._send_json(400, {"error": "invalid_json", "detail": str(exc)})
            return

        system = body.get("system", "")
        messages = body.get("messages", [])
        requested_model = body.get("model", "claude-sonnet-4-6")

        prompt_parts = []
        if system:
            if isinstance(system, list):
                system = "\n".join(
                    block.get("text", "") for block in system
                    if isinstance(block, dict)
                )
            prompt_parts.append(system)

        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, list):
                content = "\n".join(
                    block.get("text", "")
                    for block in content
                    if isinstance(block, dict) and block.get("type") == "text"
                )
            prompt_parts.append(content)

        full_prompt = "\n\n".join(prompt_parts)

        cmd = ["claude", "-p", "--output-format", "text"]
        cli_model = MODEL_ALIASES.get(requested_model, requested_model)
        if cli_model:
            cmd.extend(["--model", cli_model])

        try:
            result = subprocess.run(
                cmd,
                input=full_prompt,
                capture_output=True,
                text=True,
                timeout=180,
            )
            response_text = result.stdout.strip()
            if result.returncode != 0:
                err = result.stderr.strip()[:500]
                print(f"[proxy] claude error (rc={result.returncode}): {err}", file=sys.stderr)
                response_text = f"Error from Claude CLI: {err}"
        except subprocess.TimeoutExpired:
            response_text = "Error: Claude CLI timed out after 180s"
        except FileNotFoundError:
            response_text = "Error: 'claude' CLI not found in PATH"

        response = {
            "id": f"msg_{uuid.uuid4().hex[:24]}",
            "type": "message",
            "role": "assistant",
            "content": [{"type": "text", "text": response_text}],
            "model": requested_model,
            "stop_reason": "end_turn",
            "stop_sequence": None,
            "usage": {"input_tokens": 0, "output_tokens": 0},
        }
        self._send_json(200, response)

    def _send_json(self, status, payload):
        body = json.dumps(payload).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format, *args):
        print(f"[proxy] {args[0] if args else format}")


def main():
    parser = argparse.ArgumentParser(description="Claude Code CLI → Anthropic Messages API proxy")
    parser.add_argument("--port", type=int, default=8199, help="Port to listen on (default 8199)")
    parser.add_argument("--host", default="0.0.0.0", help="Bind address (default 0.0.0.0)")
    args = parser.parse_args()

    server = ThreadingHTTPServer((args.host, args.port), ClaudeProxyHandler)
    print(f"Claude Code proxy on http://{args.host}:{args.port}")
    print("POST /v1/messages — Anthropic Messages API; wraps `claude -p` (Max subscription)")
    print("Press Ctrl+C to stop")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
