"""
One-shot backfill: write Postgres customer-discovery interviews + insights into
Teable when the original dual-write was lost (most often because Teable auth
was broken at the time the interview was processed).

Idempotent on a per-interview basis: skips any interview whose fireflies_meeting_id
already exists as a "Fireflies ID" row in the Teable Interviews table.

Usage on the VM:
    cd /home/elmanamador/automations/vm-api
    set -a && source .env && set +a
    uv run python backfill_teable.py            # dry-run, prints what would be written
    uv run python backfill_teable.py --apply    # actually writes

Clusters are not backfilled — they are aggregations regenerated by the weekly
digest pipeline and re-deriving them per interview would create duplicates.
"""

import argparse
import asyncio
import logging
import os
import sys
import urllib.parse
import urllib.request

import asyncpg

from teable_client import (
    INTERVIEWS_TABLE,
    TeableAuthError,
    TeableClient,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("backfill_teable")

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://paperclip:paperclip@127.0.0.1:5432/discovery",
)


async def fetch_existing_teable_fireflies_ids(client: TeableClient) -> set[str]:
    """Page through the Teable Interviews table and collect every Fireflies ID."""
    ids: set[str] = set()
    skip = 0
    page_size = 200
    while True:
        path = (
            f"/api/table/{INTERVIEWS_TABLE}/record?"
            + urllib.parse.urlencode({
                "fieldKeyType": "name",
                "take": page_size,
                "skip": skip,
                "projection[]": "Fireflies ID",
            })
        )
        result = await asyncio.to_thread(client._request, "GET", path)
        records = (result or {}).get("records", [])
        if not records:
            break
        for r in records:
            fid = (r.get("fields") or {}).get("Fireflies ID")
            if fid:
                ids.add(fid)
        if len(records) < page_size:
            break
        skip += page_size
    return ids


async def fetch_missing_interviews(
    pool: asyncpg.Pool, existing_ids: set[str]
) -> list[asyncpg.Record]:
    rows = await pool.fetch(
        """
        SELECT id, date, participant_name, participant_role, company_name,
               interviewee_type, product_categories, behavioral_segment,
               demographics, summary, fireflies_meeting_id
        FROM discovery.interviews
        WHERE fireflies_meeting_id IS NOT NULL
        ORDER BY date ASC, id ASC
        """
    )
    return [r for r in rows if r["fireflies_meeting_id"] not in existing_ids]


async def fetch_insights_for(pool: asyncpg.Pool, interview_id: int) -> list[asyncpg.Record]:
    return await pool.fetch(
        """
        SELECT type, category, content, severity, sentiment, verbatim_quote
        FROM discovery.insights
        WHERE interview_id = $1
        ORDER BY id ASC
        """,
        interview_id,
    )


async def main(apply: bool) -> int:
    try:
        client = TeableClient()
    except TeableAuthError as e:
        logger.error("Cannot init Teable client: %s", e)
        return 2

    pool = await asyncpg.create_pool(DATABASE_URL, min_size=1, max_size=2)
    try:
        logger.info("Fetching Fireflies IDs already in Teable …")
        existing = await fetch_existing_teable_fireflies_ids(client)
        logger.info("Found %d existing Teable interview rows.", len(existing))

        missing = await fetch_missing_interviews(pool, existing)
        logger.info("Postgres interviews missing from Teable: %d", len(missing))

        total_insights = 0
        for row in missing:
            insights = await fetch_insights_for(pool, row["id"])
            total_insights += len(insights)
            logger.info(
                "  pg.id=%s date=%s ff=%s participant=%s insights=%d",
                row["id"],
                row["date"],
                row["fireflies_meeting_id"],
                row["participant_name"],
                len(insights),
            )

        if not apply:
            logger.info(
                "[DRY RUN] Would write %d interviews + %d insights. "
                "Re-run with --apply to commit.",
                len(missing),
                total_insights,
            )
            return 0

        written_interviews = 0
        written_insights = 0
        for row in missing:
            try:
                client.write_interview(
                    participant_name=row["participant_name"],
                    date=str(row["date"]),
                    participant_role=row["participant_role"] or "",
                    company_name=row["company_name"] or "",
                    interviewee_type=row["interviewee_type"] or "",
                    product_categories=list(row["product_categories"] or []),
                    behavioral_segment=row["behavioral_segment"] or "",
                    demographics=row["demographics"] or "",
                    summary=row["summary"] or "",
                    fireflies_meeting_id=row["fireflies_meeting_id"] or "",
                )
                written_interviews += 1
            except Exception as e:
                logger.error("Failed to write interview pg.id=%s: %s", row["id"], e)
                continue

            insights = await fetch_insights_for(pool, row["id"])
            payload = [
                {
                    "interview": row["participant_name"],
                    "type": ins["type"],
                    "category": ins["category"] or "",
                    "content": ins["content"],
                    "severity": ins["severity"] or "",
                    "sentiment": ins["sentiment"] or "",
                    "quote": ins["verbatim_quote"] or "",
                }
                for ins in insights
            ]
            if payload:
                try:
                    written_insights += client.write_insights(payload)
                except Exception as e:
                    logger.error("Failed to write insights for pg.id=%s: %s", row["id"], e)

        logger.info(
            "Backfill complete: wrote %d interviews and %d insights to Teable.",
            written_interviews,
            written_insights,
        )
        return 0
    finally:
        await pool.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Actually write to Teable (default is dry-run).")
    args = parser.parse_args()
    sys.exit(asyncio.run(main(apply=args.apply)))
