"""Generate Fireflies-style .docx transcripts.

Mirrors the format Fireflies emits when you "Download as Word" from their
dashboard:

  * Page header (2-col borderless table): meeting title left, "Meeting created
    at: <date>" right.
  * Body: one paragraph per utterance, three line-break-separated runs:
      [bold] HH:MM[:SS]
             Speaker name [INTERVIEWEE|BROCCOLI TEAM]
             Utterance text
  * Footer paragraph: "Generated by broccoli-ai".

Speaker role labels come from the pipeline's role_map (same source as the PDF
generator). No summary or action items section — Fireflies' own DOCX omits them
and we want NotebookLM to analyze raw transcript without being biased by
Fireflies' AI synthesis.
"""
import os
import re
from datetime import datetime, timezone

from docx import Document
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Cm, Inches, Pt

from fireflies import Transcript


_DEFAULT_FONT = "Arial"


def _safe_filename(title: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", title.lower())
    slug = re.sub(r"\s+", "-", slug).strip("-")
    return slug[:60]


def _format_timestamp(seconds: float) -> str:
    """`MM:SS` under one hour, `H:MM:SS` past it (matches Fireflies)."""
    total = int(seconds or 0)
    hours, rem = divmod(total, 3600)
    minutes, secs = divmod(rem, 60)
    if hours:
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


def _format_meeting_date(date_value) -> str:
    """Match Fireflies' header style: '21st Apr, 2026 - 2:30 PM'.

    Accepts an int millisecond timestamp, an ISO-ish string, or empty.
    """
    if not date_value:
        return "Unknown date"
    try:
        if isinstance(date_value, (int, float)):
            dt = datetime.fromtimestamp(date_value / 1000, tz=timezone.utc)
        else:
            dt = datetime.fromisoformat(str(date_value).replace("Z", "+00:00"))
    except Exception:
        return str(date_value)[:24]
    day = dt.day
    suffix = "th" if 11 <= (day % 100) <= 13 else {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
    return dt.strftime(f"{day}{suffix} %b, %Y - %-I:%M %p")


def _set_table_borders_none(table) -> None:
    """Strip all visible borders from a table — header table is invisible.

    OOXML requires a strict child order in <w:tblPr>: tblBorders must come
    BEFORE tblCaption / tblDescription / tblPrChange. python-docx does not
    insert tblBorders by default, so we build one and place it at the end of
    tblPr (none of the trailing elements exist on a fresh table).
    """
    tbl = table._tbl
    tblPr = tbl.tblPr
    # Replace any existing tblBorders (don't append a second one).
    for existing in tblPr.findall(qn("w:tblBorders")):
        tblPr.remove(existing)
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        b = OxmlElement(f"w:{edge}")
        b.set(qn("w:val"), "nil")
        borders.append(b)
    # OOXML order in tblPr: tblBorders comes after tblInd and before tblShd/
    # tblLayout/tblCellMar/tblLook/tblCaption/tblDescription/tblPrChange.
    # python-docx adds tblLayout + tblLook by default, so we must insert
    # tblBorders BEFORE them (otherwise the schema rejects it).
    blockers = {
        qn("w:tblShd"),
        qn("w:tblLayout"),
        qn("w:tblCellMar"),
        qn("w:tblLook"),
        qn("w:tblCaption"),
        qn("w:tblDescription"),
        qn("w:tblPrChange"),
    }
    insert_at = None
    for i, child in enumerate(tblPr):
        if child.tag in blockers:
            insert_at = i
            break
    if insert_at is not None:
        tblPr.insert(insert_at, borders)
    else:
        tblPr.append(borders)


def _build_header(section, title: str, date_str: str) -> None:
    """Page header: 2-col borderless table; title left, 'Meeting created at: …' right."""
    header = section.header
    if header.paragraphs and header.paragraphs[0].text == "":
        # python-docx pre-creates an empty paragraph; remove it so the table
        # is the first element.
        header.paragraphs[0]._element.getparent().remove(header.paragraphs[0]._element)
    table = header.add_table(rows=1, cols=2, width=Cm(16.5))
    table.autofit = False
    _set_table_borders_none(table)

    left, right = table.rows[0].cells
    left.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
    right.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

    p_left = left.paragraphs[0]
    p_left.add_run(title or "Untitled Meeting")
    p_left.alignment = WD_ALIGN_PARAGRAPH.LEFT

    p_right = right.paragraphs[0]
    p_right.add_run(f"Meeting created at: {date_str}")
    p_right.alignment = WD_ALIGN_PARAGRAPH.RIGHT


def _add_break(run) -> None:
    """Insert a soft line break inside a run (matches Fireflies' <w:br/>)."""
    br = OxmlElement("w:br")
    run._element.append(br)


def _fix_zoom_percent(doc) -> None:
    """python-docx writes <w:zoom/> with no percent attr — schema-invalid.

    Patch it post-hoc so the document validates cleanly. Word/Pages/NotebookLM
    accept the unpatched form, but failing schema validation is an avoidable
    rough edge.
    """
    settings = doc.settings.element
    zoom = settings.find(qn("w:zoom"))
    if zoom is not None and zoom.get(qn("w:percent")) is None:
        zoom.set(qn("w:percent"), "100")


def _add_utterance(doc, timestamp: str, speaker_label: str, text: str) -> None:
    """One paragraph, three line-break-separated runs: bold ts, speaker, text."""
    p = doc.add_paragraph()
    ts_run = p.add_run()
    ts_run.bold = True
    _add_break(ts_run)
    ts_run.add_text(timestamp)

    spk_run = p.add_run()
    _add_break(spk_run)
    spk_run.add_text(speaker_label)

    text_run = p.add_run()
    _add_break(text_run)
    text_run.add_text(text or "")


def _label_for(speaker: str, role_map: dict[str, str] | None) -> str:
    """Append [INTERVIEWEE] / [BROCCOLI TEAM] after the speaker name.

    Matches the same role tags used in the existing PDF generator and consumed
    by the discovery extractor / NotebookLM analysis prompts.
    """
    role = (role_map or {}).get(speaker, "external")
    tag = "BROCCOLI TEAM" if role == "internal" else "INTERVIEWEE"
    return f"{speaker} [{tag}]"


def generate_transcript_docx(
    transcript: Transcript,
    output_dir: str,
    role_map: dict[str, str] | None = None,
) -> str:
    """Render a transcript to a .docx file. Returns the absolute path."""
    filename = f"{_safe_filename(transcript.title)}-{transcript.id[:8]}.docx"
    output_path = os.path.join(output_dir, filename)

    doc = Document()

    # Per anthropics/skills@docx: set page size and font explicitly. Default is
    # A4 / Times-style — neither is what we want for US-distributed transcripts.
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    style = doc.styles["Normal"]
    style.font.name = _DEFAULT_FONT
    style.font.size = Pt(11)

    _build_header(
        section,
        title=transcript.title or "Untitled Meeting",
        date_str=_format_meeting_date(transcript.date),
    )

    # Body: one paragraph per sentence (matches Fireflies — no merging across
    # consecutive same-speaker sentences).
    if transcript.sentences:
        for sentence in transcript.sentences:
            speaker = sentence.speaker_name or "Unknown"
            _add_utterance(
                doc,
                timestamp=_format_timestamp(sentence.start_time),
                speaker_label=_label_for(speaker, role_map),
                text=sentence.text,
            )
    else:
        doc.add_paragraph("(No transcript available)")

    footer = doc.add_paragraph("Generated by broccoli-ai")
    footer.alignment = WD_ALIGN_PARAGRAPH.LEFT

    _fix_zoom_percent(doc)
    doc.save(output_path)
    return output_path
